### ISSUE TITLE
Add PHP 5.6 support

### ISSUE THREAD

**Issue by IsaacInsoll** [grasenhiller/silverstripe-wkhtmltox#2]
Hi, 
This is working fine for me in a PHP7 environment but doesn't support PHP5.6

I get the following error:
`Default value for parameters with a class type hint can only be NULL in /home/mightyminds/ss4/vendor/grasenhiller/silverstripe-wkhtmltox/src/WkFile.php on line 79`

I've resolved this by removing the word 'String' in front of the variables that define a default value and now everything is working on PHP5.6.

As Silverstripe 4 still supports PHP5.6 I think it's best that this project does as well.

**Comment by bhofstaetter** [comment]
Hi,

I'm sry but since PHP 5 is no longer officially supported and also [SilverStripe is planing to drop the PHP5 support by the end of the year](https://www.silverstripe.org/blog/our-plan-for-ending-php-5-6-support-in-silverstripe-4/) we won't provide PHP 5 support for this module.

But feel free to fork this module and make the changes for your self.
